### ISSUE TITLE
"Passing individual values" config output errors

### ISSUE THREAD

**Issue by florent-cdl** [dc7290/template-ejs-loader#11]
Hi,
I'm trying to get the current filename inside my ejs template (which include an ejs with that name) but can't get that parameter either by HtmlWebpackPlugin options or template-ejs-loader.

This is a part of my webpack.config (plugins part, sorry some quotes don't render ,so have to change "`" to "'") : 

`      ...arrayOfEntry.map(
        (page) =>
          new HtmlWebpackPlugin({
            inject: true,
            template: '${projectPaths.projectEjsTemplatesPath}/webpack-base-standard.ejs',
            filename: '../${page}.html',
            chunks: [page, "common"],
            templateParameters: {
              env: process.env.NODE_ENV,
              jsPath: projectPaths.projectJsPath,
              cssPath: projectPaths.projectScssPath,
              ejsPath: projectPaths.projectEjsPath,
              filename: page
            },
          })
      ),`

filename templateParameters always set to the first 'page' var opf the loop
I've tried (as specified in readme file)

`            template: '!${require.resolve('html-loader')}??ruleSet[1].rules[0].use[0]!${path.resolve(
              __dirname,
              '../lib/index.js'
            )}?${new URLSearchParams({
              // Use the query as an option to pass to the loader
              root: projectPaths.projectEjsTemplatesPath,
              data: JSON.stringify({
                foo: 'bar',
              }),
            })}!${projectPaths.projectEjsTemplatesPath}/webpack-base-standard.ejs',
`

but get the error
`ERROR in   Error: Child compilation failed:
  Module not found: Error: Can't resolve '/Volumes/TEST-WEBPACK/lib/index.js' in '/Volumes/TEST-WEBPACK'`

Please if someone get the solution. What I'm trying to get inside the template ejs

`<%- include('${htmlWebpackPlugin.options.ejsPath}/${htmlWebpackPlugin.options.filename}.ejs', {myvar : 'test'}) %>`

Best regards
Florent

**Comment by dc7290** [comment]
@florent-cdl

Hello.
Thank you for using our library here!

Could you please create a sample project to reproduce the error?
Or please attach `webpack.config.js`.

We might be able to figure out if the error is caused by `html-webpack-plugin`, `template-ejs-loader`, or something else.
or something else.

**Comment by florent-cdl** [comment]
Hi,

What I want to do is : 
 - have a loader that understand "include"
 - get the current filename var inside the .ejs to include the right .ejs file (code of my ejs template :  `<%- include(`${htmlWebpackPlugin.options.ejsPath}/${htmlWebpackPlugin.options.filename}.ejs`, {components : owInclude}) %>)`

I managed to get that filename but was obliged to modify your loader : I've added that line (after line 70 of node_modules/template-ejs-loader/lib/index.js )
`filename: Object.keys(this._compiler?.options.entry)[0]`
but can't keep such a solution that will be erase in update

My webpack.config.js is quite long but here is (at the message bottom) a brief view.

I just resumed entries with 2 lines but this part is a loop on multiple files like the HTMLWebpackPlugin part.

Your loader doesn't allow templateParameters as a function (but not sure it is the solution)

A more simple HTMLWebpackPlugin version I test never give me the right filename but always the first one used on the loop (event if filename is the right one in the loop below)

`    new HtmlWebpackPlugin({
      inject: true,
      template: `${projectPaths.projectEjsTemplatesPath}/webpack-base-standard.ejs`,
      filename: `../${page}.html`,
      chunks: [page, "common"],
      templateParameters: {
        env: process.env.NODE_ENV,
        jsPath: projectPaths.projectJsPath,
        cssPath: projectPaths.projectScssPath,
        ejsPath: projectPaths.projectEjsPath,
        filename: page
      },
    })`

So I tested this one to have singular parameter : 

`    new HtmlWebpackPlugin({
      inject: true,
      // template: `${projectPaths.projectEjsTemplatesPath}/webpack-base-standard.ejs`,
      template: `!${require.resolve('html-loader')}??ruleSet[1].rules[0].use[0]!${path.resolve(
        __dirname,
        '../node_modules/template-ejs-loader/lib/index.js'
      )}?${new URLSearchParams({
        // Use the query as an option to pass to the loader
        root: projectPaths.projectOutput,
        data: JSON.stringify({
          filename: page
        }),
      })}!${projectPaths.projectEjsTemplatesPath}/webpack-base-standard.ejs`,
      filename: `../${page}.html`,
      chunks: [page, "common"],
      templateParameters: {
        env: process.env.NODE_ENV,
        jsPath: projectPaths.projectJsPath,
        cssPath: projectPaths.projectScssPath,
        ejsPath: projectPaths.projectEjsPath,
        filename: page
      },
    })`

`{
  mode: 'development',
  devServer: {
    static: {
      directory: '/Volumes/TRAVAUX/PROJETS/TEST-WEBPACK/dist'
    }
  },
  entry: {
    'about-us': '/Volumes/TRAVAUX/PROJETS/TEST-WEBPACK/src/bundles/js/about-us.js',
    'account-credit-card-create': '/Volumes/TRAVAUX/PROJETS/TEST-WEBPACK/src/bundles/js/account-credit-card-create.js'
  },
  output: {
    chunkFilename: '[id].chunk.js',
    path: '/Volumes/TRAVAUX/PROJETS/TEST-WEBPACK/dist/js',
    assetModuleFilename: 'images/[hash][ext][query]',
    filename: '[name]-modern.js'
  },
  resolve: {
    extensions: [ '*', '.js', '.jsx' ],
    alias: { handlebars: 'handlebars/dist/handlebars.js' },
    modules: [ '/Volumes/TRAVAUX/PROJETS/TEST-WEBPACK/node_modules' ]
  },
  devtool: false,
  module: { rules: [ 
    {
      test: /\.ejs$/, 
      use: [
        {
          loader: 'html-loader',
          options: {
            // Disables attributes processing
            sources: false,
          },
        },
        {
          loader: 'template-ejs-loader',
          options: {data: {test:'true'}}
        }
      ],
    }
   ] },
  name: 'client-modern',
  target: 'browserslist:modern',`

**Comment by florent-cdl** [comment]
Hi,
do you find some resolutions ? or ways to have the filename parameters inside the ejs ? 

Thank you

**Comment by florent-cdl** [comment]
Hi,
I'm interested having your knowledge on that point because i'm really stopped and can't find a solution right now
Thank you

**Comment by mizok** [comment]
@florent-cdl 
Uh.. I guess you need to describe your question more clearly, since you are not able to give a reproducible repository.
(bc even me don't understand what the problem is...)

And if you want to show your .js code, you can use  (````javascript) (content) (````) , not using (`)(content)(`).

**Comment by florent-cdl** [comment]
Hi,
It's very simple : 
How can I get the current filename inside my ejs template ? As I want to include an ejs which has the same name as the filename being process (but in another template part directory)
Thank you

**Comment by mizok** [comment]
@florent-cdl 

You mean just like this?

folder structure:
````
template
├── index.ejs
├── partials1
               └──── tempA.ejs
└── partials2
               └──── tempA.ejs
````

````index.ejs
<include ''./partials1/tempA.ejs">
<include ''./partials2/tempB.ejs">
````

**Comment by mizok** [comment]
I guess I know what you are meaning about.
You want to get your current filename inside your `.ejs` template as a variable.
(But this seems to be a weird using condition, at least it is to me :neutral_face: )

**Comment by florent-cdl** [comment]
This is exactly the pb.
We have a complex site with lot of ejs files and includes
So do you know how to get that value ?

**Comment by mizok** [comment]
@florent-cdl 
I am not sure if @dc7290  is busy  by this time :(  (it's asian new year time)
I did try to contact him using twitter, but no luck.

**Comment by florent-cdl** [comment]
Great ! Thank you very much
I will wait your message
Have a nice day

**Comment by mizok** [comment]
@florent-cdl 

I think I got a temporary solution for you, but not with this loader.
You can try `ejs-loader` as an alternative.

then you can just use  the option `templateParameter` of `htmlWebpackPlugin` like below:
````javascript
new HtmlWebpackPlugin({
    filename: ...,
    template: ...,
    templateParameters:{
      filename://  filename you get.
    }
    
  })
````
And in .ejs file:

````ejs
<!DOCTYPE html>
<html lang="en">

<head></head>

<body>
  <div class="site">
    <div class="site__header-wrapper">

    </div>
    <div class="site__body">
      <!-- use temaplateParameter-->
      <h1><%= htmlWebpackPlugin.options.filename %></h1>
    </div>
    <div class="site__footer-wrapper">
       <!-- include other partial-->
      <%= require('./src/template/footer.ejs')() %>
    </div>
  </div>

</body>

</html>
````

**Comment by florent-cdl** [comment]
Hi
Thank you for the solution
I've already tried lot of ejs loaders, and this one.
I can't remember the pb with this one but I will give it a try and get back to you.
And otherwise, the evoution I give in my previous messages ?  : 
_I managed to get that filename but was obliged to modify your loader : I've added that line (after line 70 of node_modules/template-ejs-loader/lib/index.js )
filename: Object.keys(this._compiler?.options.entry)[0]
but can't keep such a solution that will be erase in update_
Best regards

**Comment by mizok** [comment]
It's not "my loader"... man lol.
I am just another user trying to fix things up.

If you do have some good idea about fixing this issue, I suggest you just make a pull request.

**Comment by dc7290** [comment]
@mizok 
Thank you for offering a solution on my behalf.

**Comment by florent-cdl** [comment]
Hi d-suke,
What do you think of the solution I give,  : 
adding this line (after line 70 of node_modules/template-ejs-loader/lib/index.js ) : 
filename: Object.keys(this.compiler?.options.entry)[0]
Or perhaps you have another solution ?
Thank you

**Comment by dc7290** [comment]
@florent-cdl 

Sorry for the late reply.

I still do not understand the problem you are having.
Are you saying that you want to pass different values to each ejs file?

**Comment by florent-cdl** [comment]
I just want to get the current filenmane as a variable inside the ejs.
I've tried the way with "queryString.stringify" but without success (as you can see in my first message)
My webpack file is quite complex, htmlwebbpack inside a loop.
No way to get that filename and use it inside the ejs template

**Comment by mizok** [comment]
@dc7290 
I just made another pull request for you about this issue.
you can check it.

**Comment by mizok** [comment]
@florent-cdl  
You can now update to v.0.7 for this issue.
And if you have any problem, feel free to make a new issue.

**Comment by florent-cdl** [comment]
Very nice, you're the best :) 
I will give it a try tomorrow.
Best regards
