### ISSUE TITLE
it is not fully supported when passing variable as parameter to ejs include function

### ISSUE THREAD

**Issue by mizok** [dc7290/template-ejs-loader#16]
**Describe the bug**

I am not sure if this should be regarded as a bug.
I found this problem last week, this happened when I used `include` within a `for` or `forEach` loop in `ejs`, just like this:

````ejs
<%
  const fs = require('fs');
   fs.readdirSync('./src/ejs-partial').forEach((filename)=>{ %>
   
   <% const filePath = `src/${filename}`%>

   <%- include(filePath)%>

  <%
   }) 
%>
````

the problem was that webpack devserver did not recognize those partial ejs files as dependency, and I thought I could tell the reason, bc we were actually using regex to detect all `include` function inside `ejs` files, which means passing variable  to `include` function is not fully supported.

But I still have no idea how to fix this..., I saw there was a `includer` option in the ejs npm package, which is capable of customize the original `include` function , but I am not sure If using `includer` is a good way to go. (gonna need a test for this I guess :( )

> includer Custom function to handle EJS includes, receives (originalPath, parsedPath) parameters, where originalPath is the path in include as-is and parsedPath is the previously resolved path. Should return an object { filename, template }, you may return only one of the properties, where filename is the final parsed path and template is the included content.

https://www.npmjs.com/package/ejs

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

- OS: [e.g. macOS 10.15.7]
- node.js: [e.g. 16.0.0]

I guess it is all version :/

**Additional context**

**Comment by dc7290** [comment]
@mizok 
Could you please describe the situation in detail?

**Comment by mizok** [comment]
Still typing the content ,sorry，it was a mistake that I did that comment.

d-suke ***@***.***>於 2022年1月23日 週日，下午5:37寫道：

**Comment by mizok** [comment]
I will finish it asap

Mizok. H ***@***.***>於 2022年1月23日 週日，下午5:39寫道：

**Comment by mizok** [comment]
The problem is actually about it is not supported when using variable in `include` function in ejs.

@dc7290  Obviously the reason is bc we are using regex to get the included files, but I am not sure if we get any way for this condition.

**Comment by dc7290** [comment]
@mizok 
This is a difficult problem.

This is because we are using a combination of ejs and webpack mechanisms, and it is difficult to incorporate the dependencies that ejs internals recognize.

For now, I came up with the following solution.
1. Add a function that allows users to add dependencies to the functions available in the ejs file.
2. When you use a variable in the `include` path, register it with that function.

We think the drawback is that it forces the user to do a somewhat tedious task.

**Comment by mizok** [comment]
> This is a difficult problem.
> 
> This is because we are using a combination of ejs and webpack mechanisms, and it is difficult to incorporate the dependencies that ejs internals recognize.
> 
> For now, I came up with the following solution.
> 
> 1. Add a function that allows users to add dependencies to the functions available in the ejs file.
> 2. When you use a variable in the `include` path, register it with that function.
> 
> We think the drawback is that it forces the user to do a somewhat tedious task.

**Comment by mizok** [comment]
> 1. Add a function that allows users to add dependencies to the functions available in the ejs file.
> 2. When you use a variable in the `include` path, register it with that function.

It do seem tedious to me...
