### ISSUE TITLE
htmlWebpackPluginTemplateCustomizer :: Always got an error "Module not found: Error: Can't resolve '/examples/webpack-ejs-starter/undefined"

### ISSUE THREAD

**Issue by florent-cdl** [dc7290/template-ejs-loader#18]
**Describe the bug**
I can't get the new htmlWebpackPluginTemplateCustomizer to work. Always the same message "module not found"

**To Reproduce**
I've created a repository to test
https://github.com/florent-cdl/ejs-webpack-sample

**Expected behavior**
I wanyt to be able to use the new htmlWebpackPluginTemplateCustomizer to pass individual variables to the ejs template

**Version**

webpack5

**Comment by dc7290** [comment]
https://github.com/florent-cdl/ejs-webpack-sample/pull/1

You can get it working with PR here.
In the case of your sample, the option name passed to `htmlWebpackPluginTemplateCustomizer ` was wrong,
 and the value passed to `data` was missing.
