### ISSUE TITLE
Data as a function

### ISSUE THREAD

**Issue by Eutrepe** [dc7290/template-ejs-loader#21]
Hi, thx for this plugin

I have a problem. How can I use data as a function in `.ejs`

Something like this: `<%= foo('something') %>`

I try by:

```
 template: htmlWebpackPluginTemplateCustomizer({

  templatePath:'./src/pages/indexPage/index.ejs',
  templateEjsLoaderOption:{ 
    data: { 
      foo: (text) => text + '_test',
    }
  }
}),
```

and/or in "simple"  htmlWebpackPlugin

```
templateParameters: {
  foo: (text) => text + '_test',
},
```

but I always get `foo is not defined`

**Comment by mizok** [comment]
@Eutrepe  I am actually not sure what function you are going to inject as data, but maybe you can try THIS instead ?

`index.ejs`:

```ejs
<% const methods = require('./src/js/methods.js') %>
<%= methods.foo('123')  %>
```
`methods.js`:

```
module.exports = {
   foo:(text)=>text
}
```

**Comment by mizok** [comment]
@Eutrepe 

Actually there is a way if you really need to inject individual function into several `ejs` files. 
You can try parse all your function into `String` ,  and call them using `eval` in `ejs` file

like this:

`index.ejs`:

```ejs
<%= eval(foo)('123')%>
```
`webpack.config.js`:

```js
template: htmlWebpackPluginTemplateCustomizer({

  templatePath:'./src/pages/indexPage/index.ejs',
  templateEjsLoaderOption:{ 
    data: { 
      foo: "(text) => text + '_test' ",
    }
  }
}),
```

BUT this is kinda dirty I think :/  .

**Comment by Eutrepe** [comment]
@dc7290  @mizok thx <3
