### ISSUE TITLE
Error when importing data

### ISSUE THREAD

**Issue by Rydestudio** [dc7290/template-ejs-loader#25]
Using data files as directed in the readme the files report as not being found. Specifically says `Cannot find module 'C:somepathsomeprojectdataindex-meta.js'` note when this happens the error message that shows is completely devoid of forward slashes which could be the cause of the issue. 

To reproduce the error simply try to use <% const meta= require('../data/index-meta.js') %> or any path with data. 

The data file is structured as shown in the readme literally exactly 

```
module.exports = {
  title: 'Webpack Starter App',
  author: 'John Doe',
  keywords: ['lorem', 'ipsum', 'dolor', 'sit', 'amet'],
  description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.',
  customFunction: function () {
    // ...
  },
}

```

**Comment by dc7290** [comment]
@Rydestudio 

Thanks for reporting the problem!

Is your OS Windows?
Maybe it is an environment-dependent bug.

Please wait a little longer as we will add Windows to the github actions test to check it out.

**Comment by Rydestudio** [comment]
Ah yes I am on windows. Thank you for the reply! Hopefully this can be made to work in windows as well.

**Comment by dc7290** [comment]
@Rydestudio 

Now supported in Ver. 0.9.3!
It worked in our test on GithubActions.
Please try it in your environment.

We would be happy to hear from you again if there are other problems.
